module.exports = {

  // Toastr message
  "TOASTR_INVALID_CREDENTIALS" : "Invalid username or password",
  "TOASTR_INVALID_EMAIL" : "Invalid email address",
  "TOASTR__INVALID_EMAIL" : " is not a valid email address",
  "TOASTR_RECIPIENTS_SHOULDNT_EMPTY" : "Recipients should not be empty",
  "TOASTR_SENT_SUCCESSFULLY" : "Your message sent successfully",
  "TOASTR_DRAFT_SAVED" : "Your draft has been saved",
  "TOASTR_MESSAGE_DELETED" : "Your message has been deleted",
  "TOASTR_MESSAGE_PERMANENTLY_DELETED" : "Your mesage has been permanently deleted",
  "TOASTR_CONNECTION_ERROR" : "There is a connection problem. Please check your internet connection and try again",
  "TOASTR_ERROR_500" : "An error occured",
  "TOASTR_MESSAGE_SELECTION_SHOULDNT_EMPTY" : "Please select minimum one message",
  "TOASTR_COULDNT_MOVE_TO_SAME_BOX" : "You are choosing the same box",
  "TOASTR_SESSION_EXPIRED" : "Your session is expired. Please try to login again",
  "TOASTR_SUCCESSFULLY_UPDATE_CONTACT" : "Contact update has been saved",
  "TOASTR_SUCCESSFULLY_ADD_CONTACT" : "New contact has been saved",
  "TOASTR_CONTACT_ALREADY_EXISTS" : "Unable to save. Contact already exists.",

  // Login
  "WELCOME" : "Welcome",
  "LOGIN" : "Login",
  "LOGIN_EMAIL" : "Email",
  "LOGIN_PASSWORD" : "Password",
  "LOGIN_REMEMBER_ME" : "Remember me",
  "LOGIN_FAQ" : "FAQ",
  "LOGIN_ABOUT" : "About",
  "LOGIN_TOS" : "Terms of Service",
  "LOGIN_FORGET_PASSWORD" : "Forgot password?",
  
  // Message
  "COMPOSE" : "Compose message",
  "QUOTA" : "Quota",
  "SEARCH_PLACEHOLDER" : "Search...",
  "RELOAD" : "Reload",
  "DATE" : "Date",
  "FROM" : "From",
  "SUBJECT" : "Subject",
  "SIZE" : "Size",
  "ARCHIVE" : "Archive",
  "TRASH" : "Trash",
  "UNREAD" : "Unread",
  "READ" : "Read",
  "REPLY" : "Reply",
  "REPLY_ALL" : "Reply All",
  "FORWARD" : "Forward",
  "DELETE" : "Delete",
  "TO" : "To",
  "DISCARD" : "Discard",
  "UPLOADING" : "Uploading...",
  "UPLOAD_FAILED" : "Failed to upload",
  "SEND" : "Send",
  "LOGOUT" : "Logout",
  "SORT_BY" : "Sort by",
  "MOVE_TO" : "Move to",
  "FLAG_AS" : "Flag as",
  "FILTER" : "Filter",
  "ATTACHMENTS" : "Attachments",
  
  // Contact
  "ADD" : "Add",
  "ADD_CONTACT" : "Add contact",
  "CONTACTS" : "Contacts",
  "NAME" : "Name",
  "EMAIL" : "Email Address",
  "ORGANIZATION" : "Organization",
  "OFFICE_ADDRESS" : "Office Address",
  "HOME_ADDRESS" : "Home Address",
  "PHONE" : "Phone",
  "EDIT" : "Edit",
  "UPDATE" : "Update",
  "CONTACT_LIST" : "Contact List",
}
