module.exports = {
  "TOASTR_INVALID_CREDENTIALS" : "Maaf, nama pengguna atau kata sandi Anda salah",
  "TOASTR_INVALID_EMAIL" : "Maaf, alamat surel tidak benar",
  "TOASTR__INVALID_EMAIL" : " bukan alamat surel yang benar",
  "TOASTR_RECIPIENTS_SHOULDNT_EMPTY" : "Alamat penerima tidak boleh kosong",
  "TOASTR_SENT_SUCCESSFULLY" : "Pesan Anda telah dikirim",
  "TOASTR_DRAFT_SAVED" : "Pesan draft Anda telah disimpan",
  "TOASTR_MESSAGE_DELETED" : "Pesan telah dihapus",
  "TOASTR_MESSAGE_PERMANENTLY_DELETED" : "Pesan telah dihapus secara permanen",
  "TOASTR_CONNECTION_ERROR" : "Sambungan bermasalah. Silakan periksa kembali koneksi Anda dan coba lagi",
  "TOASTR_ERROR_500" : "Maaf, terjadi kesalahan sistem",
  "TOASTR_MESSAGE_SELECTION_SHOULDNT_EMPTY" : "Pilih minimal satu pesan terlebih dahulu",
  "TOASTR_COULDNT_MOVE_TO_SAME_BOX" : "Anda memilih kotak surel yang sama",
  "TOASTR_SESSION_EXPIRED" : "Batas waktu sesi Anda telah habis. Silakan coba untuk masuk kembali",
  "TOASTR_SUCCESSFULLY_ADD_CONTACT" : "Kontak baru telah disimpan",
  "TOASTR_SUCCESSFULLY_UPDATE_CONTACT" : "Pembaruan kontak telah disimpan",
  "TOASTR_SUCCESSFULLY_DELETE_CONTACT" : "Kontak telah dihapus",
  "TOASTR_CONTACT_ALREADY_EXISTS" : "Gagal menyimpan. Kontak sudah pernah dibuat",
  "TOASTR_ATTACHMENT_UPLOAD_NOT_FINISHED_YET" : "Unggahan lampiran masih belum seelesai",
  
  // Login
  "WELCOME" : "Selamat Datang",
  "LOGIN" : "Masuk",
  "LOGIN_EMAIL" : "Alamat surel",
  "LOGIN_PASSWORD" : "Kata sandi",
  "LOGIN_REMEMBER_ME" : "Ingat saya",
  "LOGIN_FAQ" : "Tanya Jawab",
  "LOGIN_ABOUT" : "Tentang",
  "LOGIN_TOS" : "Syarat dan Ketentuan",
  "LOGIN_FORGET_PASSWORD" : "Lupa kata sandi?",

  // Message
  "COMPOSE" : "Tulis Surel",
  "QUOTA" : "Kuota",
  "SEARCH_PLACEHOLDER" : "Cari...",
  "RELOAD" : "Muat ulang",
  "DATE" : "Tanggal",
  "FROM" : "Pengirim",
  "SUBJECT" : "Judul",
  "SIZE" : "Ukuran",
  "ARCHIVE" : "Arsip",
  "TRASH" : "Tong Sampah",
  "UNREAD" : "Belum dibaca",
  "READ" : "Sudah dibaca",
  "REPLY" : "Balas",
  "REPLY_ALL" : "Balas ke semua",
  "FORWARD" : "Teruskan",
  "DELETE" : "Hapus",
  "TO" : "Kepada",
  "DISCARD" : "Batal",
  "UPLOAD" : "Unggah",
  "UPLOADING" : "Mengunggah...",
  "UPLOAD_FAILED" : "Gagal mengunggah",
  "SEND" : "Kirim",
  "LOGOUT" : "Keluar",
  "SORT_BY" : "Urutkan",
  "MOVE_TO" : "Pindah ke",
  "FLAG_AS" : "Tandai sebagai",
  "FILTER" : "Filter",
  "ATTACHMENTS" : "Lampiran",

  // Contact
  "ADD" : "Tambah",
  "ADD_CONTACT" : "Tambah kontak",
  "CONTACTS" : "Buku Alamat",
  "NAME" : "Nama",
  "EMAIL" : "Surat Elektronik",
  "ORGANIZATION" : "Institusi / Organisasi",
  "OFFICE_ADDRESS" : "Alamat Kantor",
  "HOME_ADDRESS" : "Alamat Rumah",
  "PHONE" : "Telepon",
  "EDIT" : "Sunting",
  "UPDATE" : "Perbarui",
  "CONTACT_LIST" : "Daftar Kontak",
}
